// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	DeletePersonById(ctx context.Context, id int64) error
	GetPersonById(ctx context.Context, id int64) (string, error)
	ListPersons(ctx context.Context, limit int32) ([]Person, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
}

var _ Querier = (*Queries)(nil)
