version: "3.3"
services:
  redis:
    image: 'redis:alpine'
    container_name: redis_docker
    ports:
      - "6379:6379"
    restart: always
    
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001"
  #   environment:
  #     - REDIS_HOST=redis_docker:6379
  #   depends_on:
  #     - redis
  #   entrypoint:
  #     [ "/app/main" ]
  #   command: [ "/app/main" ]
